### ISSUE TITLE
Example usage in Readme causes error

### ISSUE THREAD

**Issue by kingalban** [Cold-Bore-Capital/dbt-cbc-utils#10]
The README.md has good example usage of the macros, but unfortunately inline comments aren't allowed in Jinja2.

Jinja2 doesn't support comments in  `{{ }}` blocks, instead they have special `{# #}` blocks ([docs](https://jinja.palletsprojects.com/en/3.0.x/templates/#comments)).

This causes confusing errors, like so:
~~~
Compilation Error in model my_model (models/my_model.sql)
  invalid syntax for function call expression
    line 10
      {{ cbc_utils.generate_pop_columns(
~~~

**Comment by danaluhova** [comment]
+1

**Comment by coldborecapital** [comment]
Sorry for the late reply to this. My wife died in early July and I took some time off. I'm getting back to fixing up this package now. I will remove the comment from the readme file. Let me know if you have any suggestions or other problems.

**Comment by coldborecapital** [comment]
README.md has been updated in the main branch. I'm not pushing a new release just yet, but I'm actively working on the waterfall bridge macro, so this will likely be bundled into a release in the next day or so.
